In [1]:
Assignment For Numpy
Difficulty Level Beginner
Import the numpy package under the name np
import numpy as np
​
Create a null vector of size 10
arr = np.zeros(10)
arr
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Create a vector with values ranging from 10 to 49
arr1 = np.arange(10,50)
arr1
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])
Find the shape of previous array in question 3
arr1.shape
(40,)
Print the type of the previous array in question 3
arr1.dtype
dtype('int64')
Print the numpy version and the configuration
np.version
<module 'numpy.version' from '/srv/conda/envs/notebook/lib/python3.6/site-packages/numpy/version.py'>
Print the dimension of the array in question 3
arr1.ndim
1
Create a boolean array with all the True values
arrd =np.bool(10)
arrd
True
Create a two dimensional array
arr2s = np.arange(10).reshape(5,2)
arr2s
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
Create a three dimensional array
arr3s = np.arange(30).reshape(2,5,3)
arr3s
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])
Difficulty Level Easy
Reverse a vector (first element becomes last)
arr1[::-1]
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])
Create a null vector of size 10 but the fifth value which is 1
arrn = np.array([0,0,0,0,0,0,0,0,0,0])
arrn[4]=1
arrn
array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
Create a 3x3 identity matrix
arr3n= np.arange(9).reshape(3,3)
arr3n
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
arr = np.array([1, 2, 3, 4, 5])

Convert the data type of the given array from int to float
arr5= np.array(([1,2,3,4,5]),dtype="float64")
arr5.astype('float64')
arr5.dtype
dtype('float64')
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
 arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.],
​
               [4., 5., 6.]]) 
​
arr2 = np.array([[0., 4., 1.],
​
              [7., 2., 12.]])
arrm = arr1*arr2
arrm
​
​
array([[ 0.,  8.,  3.],
       [28., 10., 72.]])
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])
 arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

Make an array by comparing both the arrays provided above
rr1 = np.array([[1., 2., 3.],
​
               [4., 5., 6.]])
​
rr2 = np.array([[0., 4., 1.],
​
               [7., 2., 12.]])
arrc = rr1 == rr2
arrc
​
array([[False, False, False],
       [False, False, False]])
Extract all odd numbers from arr with values(0-9)
a= np.arange(10)
a[a % 2 ==1]
​
​
array([1, 3, 5, 7, 9])
Replace all odd numbers to -1 from previous array
a[a%2==1]= -1
a
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12
b = np.arange(10)
b[5:9]=12
b
array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])
Create a 2d array with 1 on the border and 0 inside
c =np.ones((4,4))
c
c[1:-1,1:-1]=0
c
array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])
Difficulty Level Medium
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

Replace the value 5 to 12
e = np.array([[1,2,3],[4,5,6],[7,8,9]])
e[1,1]=12
e
​
array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Convert all the values of 1st array to 64
f =np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
​
f[0:1,0:1]=64
f
​
array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])
Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
g =np.array([[0,1,2,3,4],[5,6,7,8,9]])
h=np.ravel(g)
h
​
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
r =np.array([[0,1,2,3,4],[5,6,7,8,9]])
r[1,1]
6
Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
j=np.arange(16).reshape(4,4)
​
j[0:2,3:4]
array([[3],
       [7]])
Create a 10x10 array with random values and find the minimum and maximum values
t= np.random.randn(10,10)
g=np.min(t),np.max(t)
g
(-3.165183788130698, 2.149264522666588)
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= np.intersect1d(a, b)
c
array([2, 4])
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= np.ind1d(a, b)
c
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-158-8f1d88e31b9f> in <module>
      1 a = np.array([1,2,3,2,3,4,3,4,5,6])
      2 b = np.array([7,2,10,2,7,4,9,4,9,8])
----> 3 c= np.ind1d(a, b)
      4 c

AttributeError: module 'numpy' has no attribute 'ind1d'


names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data["will"]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-159-c1f67f9f560a> in <module>
      1 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
      2 data = np.random.randn(7, 4)
----> 3 data["will"]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices


names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

Find all the values from array data where the values from array names are not equal to Will and Joe
​
Difficulty Level Hard
Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
​
Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
​
Swap axes of the array you created in Question 32
​
Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
​
Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
​
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

Find the unique names and sort them out!
​
a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

From array a remove all items present in array b
​
Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])
simarr = np.array([[34,43,73],[82,22,12],[53,94,66]])
sarr = np.split()
sarr
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-f1247418c880> in <module>
      1 simarr = np.array([[34,43,73],[82,22,12],[53,94,66]])
----> 2 sarr = np.split([0,2])
      3 sarr

<__array_function__ internals> in split(*args, **kwargs)

TypeError: _split_dispatcher() missing 1 required positional argument: 'indices_or_sections'


x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix
Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
import numpy as np
and_arr = np.random.uniform(1,16, size=(5,3))
and_arr
arrw=np.random.randint(1,17,size= (5,3))+np.random.random((5,3))
arrw
​
array([[ 6.57867187,  1.14800919,  1.51339849],
       [10.21284769,  8.20311802,  6.73358342],
       [ 8.66256699,  6.61429328,  8.98420452],
       [12.08486156, 16.0858336 ,  7.45731948],
       [ 6.88279629,  1.06938453,  6.41326677]])
​
​
array([[[ 6.59365612,  2.31469509, 13.6377528 ,  1.17807571],
        [10.2216525 , 16.94812608, 11.22247869,  2.50187795]],

       [[ 1.37246999, 10.76787132,  5.74067744,  7.9908757 ],
        [16.1124127 ,  4.73371888,  5.46625299,  4.28025814]]])
Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
arrw=np.random.randint(1,17,size= (2,2,4))+np.random.random((2,2,4))
arrw
and_arr = np.random.uniform(1,17, size=(2,2,4))
and_arr
array([[[ 6.69203569,  8.47834402,  2.90278419, 11.78195671],
        [11.67543806,  5.36555124,  1.57411536, 11.77911549]],

       [[12.70671611,  7.27934222,  3.9044527 , 16.45894778],
        [15.3546602 , 16.53099007,  6.77653287, 15.49927387]]])
​
​
Swap axes of the array you created in Question 32
arrf=np.swapaxes(arrw,0,2)
arrf
array([[[15.98111989,  7.33581623],
        [ 5.27902755,  7.7980661 ]],

       [[12.27571923,  4.17766788],
        [ 1.24111439,  2.10039641]],

       [[ 5.16244954,  9.51612275],
        [ 4.44410209, 12.53316943]],

       [[ 2.71591005,  5.87896958],
        [ 8.32678509, 10.19949905]]])
Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
arrt=np.arange(10)
arrsq=np.sqrt(arrt)
arrsq
​
​
array([  6,  11,   9,   5,  11, -10,   4, -12,  -1,  -6,  -1,  15],
      dtype=int32)
Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
x= np.array((np.random.randn(12)*10),dtype='int32')
y=np.array((np.random.randn(12)*10),dtype='int32')
​
arrm=np.maximum(x,y)
arrm
array([11, 14, 10,  6, 10,  0, 17, 17,  9,  8, 11, 21], dtype=int32)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
arru=np.unique(names)
arru
array(['Bob', 'Joe', 'Will'], dtype='<U4')
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
arrem=np.setdiff1d(a,b)
arrem
​
#---
#From array a remove all items present in array b
​
​
array([1, 2, 3, 4])
import numpy as np
Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])
​
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
​
newColumn = np.array([[10,10,10]])
neew=np.hsplit(sampleArray,[3])
neew
​
[array([[34, 43, 73],
        [82, 22, 12],
        [53, 94, 66]]),
 array([], shape=(3, 0), dtype=int64)

x = np.array ([[1,2,3],[4,5,6]])
y = np.array([[6,23],[1,7],[8,9]])
mdo= np.dot(x,y)
mdo
array([[ 32,  64],
       [ 77, 181]])
Generate a matrix of 20 random values and find its cumulative sum
arr = np.array((np.random.randn(20)*10),dtype='int32')
arrs = np.cumsum(arr)
arrs
array([ -4,   3,  22,  29,   7,  18,  11,  21,  17,  19,  29,  45,  37,
        45,  60,  70,  77,  93, 101,  95])
​
array([ -4,   7,  19,   7, -22,  11,  -7,  10,  -4,   2,  10,  16,  -8,
         8,  15,  10,   7,  16,   8,  -6], dtype=int32)
​

In [8]:
%time for i in range (1,10): r = arr * 2



Numpy_Assignment_2::
import numpy as np
a=np.arange(1,10).reshape(3,3)
b=np.arange(11,20).reshape(3,3)
c=np.arange(31,40).reshape(3,3)
print(np.stack((a,b)))
print("%%%%%%%%%%%%%")
print(np.hstack((a,b)))
print("%%%%%%%%%%%%%")
print(np.vstack((a,b)))
print("%%%%%%%%%%%%%")
print(np.concatenate((a,b),axis=0))
print("%%%%%%%%%%%%%")
print(np.dstack((a,b,c)))
r=np.arange(1,10)
print("%%%%%%%%%%%%%")
print(np.hstack((r)))
print("%%%%%%%%%%%%%")
print(np.vstack(r))
​
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
%%%%%%%%%%%%%
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
%%%%%%%%%%%%%
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
%%%%%%%%%%%%%
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
%%%%%%%%%%%%%
[[[ 1 11 31]
  [ 2 12 32]
  [ 3 13 33]]

 [[ 4 14 34]
  [ 5 15 35]
  [ 6 16 36]]

 [[ 7 17 37]
  [ 8 18 38]
  [ 9 19 39]]]
%%%%%%%%%%%%%
[1 2 3 4 5 6 7 8 9]
%%%%%%%%%%%%%
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Question:1
Convert a 1D array to a 2D array with 2 rows?
Desired output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
d =np.array(np.arange(5))
e=np.array(np.arange(1,6))
np.vstack((d,e))
array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5]])
Question:2
How to stack two arrays vertically?
Desired Output::
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
      [1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1]])
d =np.array(np.arange(10).reshape(2,5))
e=np.array(np.arange(10,20).reshape(2,5))
np.vstack((d,e))
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])
Question:3
How to stack two arrays horizontally?
Desired Output::
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
      [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
d =np.array(np.arange(10).reshape(2,5))
e=np.array(np.arange(10,20).reshape(2,5))
np.hstack((d,e))
array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])
Question:4
How to convert an array of arrays into a flat 1d array?
Desired Output::
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
d =np.array(np.arange(10).reshape(2,5))
np.ravel(d)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Question:5
How to Convert higher dimension into one dimension?
Desired Output::
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
d =np.array(np.arange(20).reshape(5,2,2))
np.ravel(d)
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])
Question:6
Convert one dimension to higher dimension?
Desired Output::
array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])
d =np.array(np.arange(10))
np.reshape(d,(2,5))
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
Question:7
Create 5x5 an array and find the square of an array?
d =np.array(np.arange(25).reshape(5,5))
#np.square(d) or
f=d**2
f
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])
Question:8
Create 5x6 an array and find the mean?
d =np.array(np.arange(30).reshape(5,6))
np.mean(d)
14.5
Question:9
Find the standard deviation of the previous array in Q8?
d =np.array(np.arange(30).reshape(5,6))
np.std(d)
8.65544144839919
Question:10
Find the median of the previous array in Q8?
d =np.array(np.arange(30).reshape(5,6))
np.median(d)
14.5
Question:11
Find the transpose of the previous array in Q8?
np.transpose(d)
array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])
Question:12
Create a 4x4 an array and find the sum of diagonal elements?
d =np.array(np.arange(16).reshape(4,4))
np.trace(d)
30
Question:13
Find the determinant of the previous array in Q12?
d =np.array(np.arange(16).reshape(4,4))
np.linalg.det(d)
0.0
Question:14
Find the 5th and 95th percentile of an array?
d =np.array(np.arange(16))
np.percentile(d,5)
np.percentile(d,95)
14.25
Question:15
How to find if a given array has any null values?
d =np.array(np.arange(16))
(d==0).any()
True


SyntaxError: invalid syntax (<ipython-input-1-53e83e2836a6>, line 1)