# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [1]:
#type your code here
import numpy as np

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [7]:
#type your code here
cupcakes = np.array([2,0.75,2,1,0.5])
print(f"This is the array of a cupcakes {cupcakes}")

This is the array of a cupcakes [2.   0.75 2.   1.   0.5 ]


3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [9]:
#type your code here
import csv
from numpy import genfromtxt
recipes =np.genfromtxt("recipes.csv",delimiter=",")
recipes=np.array(recipes)
print(recipes)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [57]:
#type your code here
print("Recipe"  "         "  "Cups of Flour" "   cups of sugar  "       "Eggs" "   "  "Cups of Milk"  "   "  "Cups of Butter")
print(f"cupcakes             {recipes[0][0]}        {recipes[0][1]}         {recipes[0][2]}       {recipes[0][3]}          {recipes[0][4]}  ")
print(f"pancake              {recipes[1][0]}        {recipes[1][1]}         {recipes[1][2]}       {recipes[1][3]}          {recipes[1][4]}    ")
print(f"Cookie               {recipes[2][0]}        {recipes[2][1]}         {recipes[2][2]}       {recipes[2][3]}          {recipes[2][4]} ")
print(f"Bread                {recipes[3][0]}        {recipes[3][1]}         {recipes[3][2]}       {recipes[3][3]}          {recipes[3][4]} ")
#print(f"Bread...... {recipes[3:4,0:5]}")



Recipe         Cups of Flour   cups of sugar  Eggs   Cups of Milk   Cups of Butter
cupcakes             2.0        0.75         2.0       1.0          0.5  
pancake              1.0        0.125         1.0       1.0          0.125    
Cookie               2.75        1.5         1.0       0.0          1.0 
Bread                4.0        0.5         2.0       2.0          0.5 


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [53]:
#type your code here
eggs =recipes[::,2:3]
eggs

array([[2.],
       [1.],
       [1.],
       [2.]])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [54]:
#type your code here
eggs==1

array([[False],
       [ True],
       [ True],
       [False]])

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [56]:
#type your code here
cookies=recipes[2]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [59]:
#type your code here
double_batch=cupcakes*cupcakes
double_batch

array([4.    , 0.5625, 4.    , 1.    , 0.25  ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [60]:
#type your code here
grocery_list=[cookies,double_batch]
grocery_list

[array([2.75, 1.5 , 1.  , 0.  , 1.  ]),
 array([4.    , 0.5625, 4.    , 1.    , 0.25  ])]